### ISSUE TITLE
PR request - support for AS7261 sensor

### ISSUE THREAD

**Issue by ufanders** [sparkfun/SparkFun_AS726X_Arduino_Library#4]
Hi there,

I've implemented and tested support for the AS7261. Would you mind allowing me to submit a PR?

Thanks!

**Comment by nseidle** [comment]
Yes please! Thank you. I'll review it as best I can but I don't think I have good hardware to test it out on so I may have to trust your testing.

**Comment by ufanders** [comment]
Awesome, thanks! FWIW I didn't modify any existing routines, except detection of an additional hardware ID in ::begin(). I'll submit a PR shortly.

**Comment by ufanders** [comment]
Hmm, I'm still unable to create one - how should we do this?

**Comment by nseidle** [comment]
Thanks! Merged. Version will be released momentarily.
