### ISSUE TITLE
How to calibrate 410nm and 435nm channels

### ISSUE THREAD

**Issue by kieranallain** [sparkfun/SparkFun_AS726X_Arduino_Library#9]
Hello,

I am using an AS7265X sensor with your AS726X.h library and am wondering what getCalibrated functions access the 410nm and 435nm channels. I tried getCalibratedA() and getCalibratedB() as this is what it says in the datasheet, but those aren't listed in your source code and it gives an error, obviously. I've also tried getCalibratedR(), getCalibratedS(), getCalibratedU() and getCalibratedV(), but I'm pretty sure these aren't right either. Any help would be appreciated.

**Comment by malcolm-sparkfun** [comment]
Currently, we have different libraries for the AS7265x and AS726x. For your application, it sounds like you are interested in the other library (the one for the AS7265x). You can find it here: [https://github.com/sparkfun/SparkFun_AS7265x_Arduino_Library/blob/main/src/SparkFun_AS7265X.h](https://github.com/sparkfun/SparkFun_AS7265x_Arduino_Library/blob/main/src/SparkFun_AS7265X.h)

It looks like that header contains the getCalibratedA() and getCailbratedB() functions that you are interested in
